osx_image: xcode10.2
language: objective-c
env:
  global:
    - PROJECT="Carte.xcodeproj"
    - SCHEME="Carte-Package"
    - IOS_SDK="iphonesimulator12.2"
  matrix:
    - SDK="$IOS_SDK"      DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=12.2"

install:
  - swift --version
  - gem update --system

before_script:
  - set -o pipefail
  - swift package generate-xcodeproj

script:
  - xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - rake test

after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist -J 'Carte'
